div/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'admin_user#login'
  # エラーページテスト用
  # get '*path', to: 'application#render_500'
  # get '*path', to: 'application#render_404'

  scope 'admin_user' do
    get '/new', to: 'admin_user#new', as: 'admin_new'
    post '/signup', to: 'admin_user#signup'
    get '/login', to: 'auth#new'
    post '/login', to: 'auth#login'
    get '/index', to: 'admin_user#index'
    # delete '/logout', to: 'auth#logout', as: 'logout'
    post '/logout', to: 'auth#logout', as: 'logout'
  end

  get '/home', to: 'admin_user#index', as: 'home'

  scope 'item' do
    get '/new', to: 'items#new'
    post '/create', to: 'items#create'
    get '/index', to: 'items#index', as: 'item_index'
    get '/edit/:id', to: 'items#edit', as: 'edit_item'
    post '/update', to: 'items#update'
    # delete '/delete/:id', to: 'items#delete', as: 'delete_item'
    post '/delete/:id', to: 'items#delete', as: 'delete_item'
  end

  scope 'slider' do
    get '/new', to: 'slider#new', as: 'slider_new'
    post '/create', to: 'slider#create'
    get '/index', to: 'slider#index', as: 'slider_index'
    post '/update', to: 'slider#update'
    delete '/delete/:id', to: 'slider#delete', as: 'slider_item'
  end

  scope 'schedule' do
    get '/new', to: 'schedules#new'
    post '/create', to: 'schedules#create'
    get '/index', to: 'schedules#index', as: 'schedule_index'
    get '/edit/:id', to: 'schedules#edit'
    delete '/delete', to: 'schedules#delete', as: 'schedule_delete'
    post '/update', to: 'schedules#update'
  end

  scope 'google_api' do
    post '/create', to: 'google_api#create'
    put '/update', to: 'google_api#update'
    get '/find', to: 'google_api#find'
  end

  scope 'users' do
    get '/index', to: 'users#index'
  end

  scope 'purchase' do
    get '/index', to: 'purchase#index', as: 'purchase_index'
  end

  get 'mail', to: 'send_mail#mail'
  get 'mail_comp', to: 'send_mail#mail_comp'
  post 'mail', to: 'send_mail#send_mail'
  post 'bulk_mail', to: 'send_mail#bulk_send_mail'

  scope 'calendar' do
    get '/get', to: 'admin_user#get_calender'
  end
end

div/app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < BaseModel # rubocop:disable Style/Documentation
  attr_accessor :password, :email

  def signup(params)
    res = execute_api('admin_user/signup', params, method: 'post')
    convert_boolean(res)
  end

  def login(params)
    res = execute_api('admin_user/login', params, method: 'post')
    convert_boolean(res)
  end

  def get_admin_user(params)
    execute_api('admin_user/get_admin_user', params, method: 'get')
  end
end

div/app/controllers/admin_user_controller.rb
# frozen_string_literal: true

require 'date'
class AdminUserController < ApplicationController # rubocop:disable Style/Documentation
  skip_before_action :check_logined, only: %i[new signup]
  skip_before_action :verify_authenticity_token
  after_action :set_csrf_token_header
  def new
    @admin_user = AdminUser.new
  end

  def signup
    @admin_user = AdminUser.new(admin_user_params)
    res = @admin_user.signup(admin_user_params)
    if res == true
      session[:limit] = Time.now + Settings.session_limit.to_i
      admin_user = @admin_user.get_admin_user(admin_user_params)
      session[:user] = admin_user
      redirect_to home_path
    else
      render action: 'new'
    end
  end

  def index
    @schedule_instance = Schedule.new
    @google_api = GoogleApi.new
    @db_google_api = @google_api.find(@current_user["id"])
    session[:user] = session[:user].symbolize_keys
  end

  def get_calender # rubocop:disable Naming/AccessorMethodName
    admin_user = AdminUser.new
    res = admin_user.get_admin_user(params.permit(:email))
    render json: res
  end

  private

  def admin_user_params
    params.require(:admin_user).permit(:email, :password)
  end
end

div/app/views/admin_user/_googl_api_create_form.html.erb
<div class="p-5">
  <%= form_for @google_api, url: "/google_api/create", multipart: true do |f| %>
    <div class="mb-3">
      <%= f.label :api_key, "API_KEY" ,class: 'form-label' %>
      <%=  f.password_field :api_key, placeholder: '',required: true,class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :calendar_id, "カレンダーID" ,class: 'form-label' %>
      <%=  f.text_field :calendar_id, placeholder: '',required: true,class: 'form-control' %>
      <%=  f.hidden_field :user_id, placeholder: '',required: true,class: 'form-control', value: @current_user["id"] %>
    </div>
    <div class="mt-3" style="margin-top: 20px;">
        <%= submit_tag "登録",class: "btn btn-primary mb-5" %>
      </div>
  <% end %>
</div>

div/app/views/admin_user/_googl_api_update_form.html.erb
<div class="p-5">
  <%= form_for @google_api, url: "/google_api/update", method: 'put', multipart: true do |f| %>
    <div class="mb-3">
      <%= f.label :api_key, "API_KEY" ,class: 'form-label' %>
      <%=  f.password_field :api_key, placeholder: '',required: true,class: 'form-control', value: @db_google_api[:api_key] %>
    </div>
    <div class="mb-3">
      <%= f.label :calendar_id, "カレンダーID" ,class: 'form-label' %>
      <%=  f.text_field :calendar_id, placeholder: '',required: true,class: 'form-control', value: @db_google_api[:calendar_id] %>
      <%=  f.hidden_field :user_id, placeholder: '',required: true,class: 'form-control', value: @current_user["id"] %>
    </div>
    <div class="mt-3" style="margin-top: 20px;">
        <%= submit_tag "更新",class: "btn btn-primary mb-5" %>
      </div>
  <% end %>
</div>

div/app/views/admin_user/_notice.html.erb
<% if notice.present? %>
<%=  notice %>
<% end %>
<% if alert.present? %>
<%=  alert %>
<% end %>

div/app/views/admin_user/index.html.erb
<% if flash[:notice].present? %>
  <p class="notice-line js-toggle-msg"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert].present? %>
  <p class="alert-line js-toggle-msg"><%= flash[:alert] %></p>
<% end %>
<%= render 'layouts/error', model: @schedule_instance %>
<%= render 'layouts/error', model: @google_api %>
<% if @db_google_api.blank? %>
  <%= render 'admin_user/googl_api_create_form' %>
<% else %>
  <%= render 'admin_user/googl_api_update_form' %>
<% end %>

<div id="calendar" class="mt-5"  data-email=<%= session[:user][:email]%>></div>

<%= render 'admin_user/modal/schedule_create', locals: { schedule_instance: @schedule_instance } %>
<%= render 'admin_user/modal/schedule_edit', locals: { schedule_instance: @schedule_instance } %>

div/app/views/admin_user/login.html.erb
<div class="container mt-5">
    <h2>ログイン</h2>
    <%= render 'layouts/error', model: @admin_user %>
    <%= form_for @admin_user, url: {action: :login} do |f| %>
        <div class="mb-3">
            <%= f.label :email,class: 'form-label' %>
            <%=  f.text_field :email, placeholder: 'E-mail',required: true,class: 'form-control' %>
        </div>
        <div class="mb-3">
            <%= f.label :password,class: 'form-label' %>
            <%=  f.password_field :password, placeholder: 'Password',required: true,class: 'form-control' %>
        </div>
        <div class="mt-3" style="margin-top: 20px;">
            <%= submit_tag "ログイン",class: "btn btn-primary" %>
        </div>
    <% end %>
    <%= link_to "新規登録", admin_new_path %>
</div>

div/app/views/admin_user/new.html.erb
<div class="container mt-5">
    <h2>新規登録</h2>
    <%= render 'layouts/error', model: @admin_user %>
    <%= form_for @admin_user, url: {action: :signup} do |f| %>
        <div class="mb-3">
            <%= f.label :email,class: 'form-label' %>
            <%=  f.text_field :email, placeholder: 'E-mail',required: true,class: 'form-control' %>
        </div>
        <div class="mb-3">
            <%= f.label :password,class: 'form-label' %>
            <%=  f.password_field :password, placeholder: 'Password',required: true,class: 'form-control' %>
        </div>
        <div class="mt-3" style="margin-top: 20px;">
            <%= submit_tag "新規登録",class: "btn btn-primary" %>
        </div>
    <% end %>
        <div class="mt-3">
      <%= link_to "ログイン", login_path %>
    </div>
</div>