div/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'admin_user#login'
  # エラーページテスト用
  # get '*path', to: 'application#render_500'
  # get '*path', to: 'application#render_404'

  scope 'admin_user' do
    get '/new', to: 'admin_user#new', as: 'admin_new'
    post '/signup', to: 'admin_user#signup'
    get '/login', to: 'auth#new'
    post '/login', to: 'auth#login'
    get '/index', to: 'admin_user#index'
    # delete '/logout', to: 'auth#logout', as: 'logout'
    post '/logout', to: 'auth#logout', as: 'logout'
  end

  get '/home', to: 'admin_user#index', as: 'home'

  scope 'item' do
    get '/new', to: 'items#new'
    post '/create', to: 'items#create'
    get '/index', to: 'items#index', as: 'item_index'
    get '/edit/:id', to: 'items#edit', as: 'edit_item'
    post '/update', to: 'items#update'
    # delete '/delete/:id', to: 'items#delete', as: 'delete_item'
    post '/delete/:id', to: 'items#delete', as: 'delete_item'
  end

  scope 'slider' do
    get '/new', to: 'slider#new', as: 'slider_new'
    post '/create', to: 'slider#create'
    get '/index', to: 'slider#index', as: 'slider_index'
    post '/update', to: 'slider#update'
    delete '/delete/:id', to: 'slider#delete', as: 'slider_item'
  end

  scope 'schedule' do
    get '/new', to: 'schedules#new'
    post '/create', to: 'schedules#create'
    get '/index', to: 'schedules#index', as: 'schedule_index'
    get '/edit/:id', to: 'schedules#edit'
    delete '/delete', to: 'schedules#delete', as: 'schedule_delete'
    post '/update', to: 'schedules#update'
  end

  scope 'google_api' do
    post '/create', to: 'google_api#create'
    put '/update', to: 'google_api#update'
    get '/find', to: 'google_api#find'
  end

  scope 'users' do
    get '/index', to: 'users#index'
  end

  scope 'purchase' do
    get '/index', to: 'purchase#index', as: 'purchase_index'
  end

  get 'mail', to: 'send_mail#mail'
  get 'mail_comp', to: 'send_mail#mail_comp'
  post 'mail', to: 'send_mail#send_mail'
  post 'bulk_mail', to: 'send_mail#bulk_send_mail'

  scope 'calendar' do
    get '/get', to: 'admin_user#get_calender'
  end
end

div/app/models/purchase.rb
# frozen_string_literal: true

class Purchase < BaseModel # rubocop:disable Style/Documentation
  attr_accessor :customerId,
                :itemId


  def create(params); end

  def update(params); end

  def index
    purchase = execute_api('purchase/index', method: 'get')
    make_list(purchase)
  end
end

div/app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  def index
    purchase = Purchase.new
    @data = SendMail.new
    @purchase = Kaminari.paginate_array(purchase.index).page(params[:page]).per(5)
  end

  private

end

div/app/views/purchase/index.html.erb
<%= render 'layouts/error', model: @data %>
<%= render partial: 'layouts/flash_message' %>
<h2 class="mt-5">注文一覧</h2>
<table class="table table-dark table-striped">
<thead>
  <tr>
    <th scope="col">お名前</th>
    <th scope="col">商品</th>
    <th scope="col">注文個数</th>
    <th scope="col">注文日</th>
    <th scope="col">対応</th>
    <th scope="col">発送日</th>
    <th scope="col"></th>
  </tr>
</thead>
<tbody>
<% @purchase.each_with_index do |p, idx| %>
    <tr>
      <td><%= p[:customer_name] %></td>
      <td><%= p[:item_name] %></td>
      <td><%= p[:quantity] %></td>
      <td><%= format_date(p[:createdAt]) %></td>
      <td>
      <!-- Button trigger modal -->
      <% if p[:support_flag] %>
        <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#staticBackdrop<%= idx %>"  disabled >
          発送済み
        </button>
      <% else %>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop<%= idx %>" >
          ステータス変更
        </button>

      <% end %>

        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop<%= idx %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" style="color: #333;" id="staticBackdropLabel">メール送信</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" style="color: #333;">
                <%= p[:customer_name] %>様に配送した旨のメールをお送りします。
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                 <%= form_with(model: @data ,url: mail_path, html:{class: 'form-group'}) do |f| %>
                    <%= f.hidden_field :state,class: 'form-control', value: "#{p[:state]}" %>
                    <%= f.hidden_field :country,class: 'form-control', value: "#{p[:country]}" %>
                    <%= f.hidden_field :postal_code,class: 'form-control', value: "#{p[:postal_code]}" %>
                    <%= f.hidden_field :line1,class: 'form-control', value: "#{p[:line1]}" %>
                    <%= f.hidden_field :line2,class: 'form-control', value: "#{p[:line2]}" %>
                    <%= f.hidden_field :purchase_id,class: 'form-control', value: "#{p[:purchase_id]}" %>
                    <%= f.hidden_field :email,class: 'form-control', value: "#{p[:email]}" %>
                    <%= f.hidden_field :item,class: 'form-control', value: "#{p[:item_name]}" %>
                    <%= f.submit "送信", class: 'btn btn-primary' %>
                  <% end %>
              </div>
            </div>
          </div>
        </div>

      </td>
      <td>
      <% if p[:support_flag] %><%= format_date(p[:updatedAt]) %><% else %>-<% end %>
      </td>
      <td>
        <% unless p[:support_flag] %>
          <%= check_box_tag "item_ids[]", nil, false, class: 'js-form-select', data: { index: idx } %>
        <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>
<!-- Modal -->
<div class="modal fade" id="checkBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="checkBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" style="color: #333;" id="staticBackdropLabel">メール送信</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" style="color: #333;">
        メールをお送りします。
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form_with(url: bulk_mail_path, html:{class: 'form-group'}) do |f| %>
            <% @purchase.each_with_index do |p, idx| %>
              <%= f.hidden_field 'send_mail[state][]', class: 'form-control', id: "state_field#{idx}", value: "#{p[:state]}", disabled: true %>
              <%= f.hidden_field 'send_mail[country][]',class: 'form-control', id: "country_field#{idx}", value: "#{p[:country]}", disabled: true %>
              <%= f.hidden_field 'send_mail[postal_code][]',class: 'form-control', id: "postal_field#{idx}", value: "#{p[:postal_code]}", disabled: true %>
              <%= f.hidden_field 'send_mail[line1][]',class: 'form-control', id: "line1_field#{idx}", value: "#{p[:line1]}", disabled: true %>
              <%= f.hidden_field 'send_mail[line2][]',class: 'form-control',id: "line2_field#{idx}",  value: "#{p[:line2]}", disabled: true %>
              <%= f.hidden_field 'send_mail[purchase_id][]',class: 'form-control',id: "purchase_field#{idx}",  value: "#{p[:purchase_id]}", disabled: true %>
              <%= f.hidden_field 'send_mail[email][]',class: 'form-control', id: "email_field#{idx}",  value: "#{p[:email]}", disabled: true %>
              <%= f.hidden_field 'send_mail[item][]',class: 'form-control',id: "item_field#{idx}",  value: "#{p[:item_name]}", disabled: true %>
              <%= f.hidden_field 'send_mail[customer_id][]',class: 'form-control',id: "customer_id_field#{idx}",  value: "#{p[:customer_id]}", disabled: true %>
            <% end %>
            <%= f.submit "一括ステータス変更", class: 'btn btn-primary js-check-submit', disabled: true %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<div class="d-flex justify-content-end">
  <button type="button" class="btn btn-info js-check-submit" data-bs-toggle="modal" data-bs-target="#checkBackdrop" >
    一括ステータス変更
  </button>
</div>
    <%= paginate @purchase, theme: 'twitter-bootstrap-4' %>