div/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'admin_user#login'
  # エラーページテスト用
  # get '*path', to: 'application#render_500'
  # get '*path', to: 'application#render_404'

  scope 'admin_user' do
    get '/new', to: 'admin_user#new', as: 'admin_new'
    post '/signup', to: 'admin_user#signup'
    get '/login', to: 'auth#new'
    post '/login', to: 'auth#login'
    get '/index', to: 'admin_user#index'
    # delete '/logout', to: 'auth#logout', as: 'logout'
    post '/logout', to: 'auth#logout', as: 'logout'
  end

  get '/home', to: 'admin_user#index', as: 'home'

  scope 'item' do
    get '/new', to: 'items#new'
    post '/create', to: 'items#create'
    get '/index', to: 'items#index', as: 'item_index'
    get '/edit/:id', to: 'items#edit', as: 'edit_item'
    post '/update', to: 'items#update'
    # delete '/delete/:id', to: 'items#delete', as: 'delete_item'
    post '/delete/:id', to: 'items#delete', as: 'delete_item'
  end

  scope 'slider' do
    get '/new', to: 'slider#new', as: 'slider_new'
    post '/create', to: 'slider#create'
    get '/index', to: 'slider#index', as: 'slider_index'
    post '/update', to: 'slider#update'
    delete '/delete/:id', to: 'slider#delete', as: 'slider_item'
  end

  scope 'schedule' do
    get '/new', to: 'schedules#new'
    post '/create', to: 'schedules#create'
    get '/index', to: 'schedules#index', as: 'schedule_index'
    get '/edit/:id', to: 'schedules#edit'
    delete '/delete', to: 'schedules#delete', as: 'schedule_delete'
    post '/update', to: 'schedules#update'
  end

  scope 'google_api' do
    post '/create', to: 'google_api#create'
    put '/update', to: 'google_api#update'
    get '/find', to: 'google_api#find'
  end

  scope 'users' do
    get '/index', to: 'users#index'
  end

  scope 'purchase' do
    get '/index', to: 'purchase#index', as: 'purchase_index'
  end

  get 'mail', to: 'send_mail#mail'
  get 'mail_comp', to: 'send_mail#mail_comp'
  post 'mail', to: 'send_mail#send_mail'
  post 'bulk_mail', to: 'send_mail#bulk_send_mail'

  scope 'calendar' do
    get '/get', to: 'admin_user#get_calender'
  end
end

div/app/models/item.rb
# frozen_string_literal: true

class Item < BaseModel # rubocop:disable Style/Documentation
  attr_accessor :id,
                :name,
                :price,
                :description,
                :images,
                :postage,
                :inventory,
                :maji_flag,
                :action,
                :image1,
                :image2,
                :iamge3,
                :image4

  def create(params)
    res = execute_api('item/create', params, method: 'post')
    convert_boolean(res)
  end

  def update(params)
    res = execute_api('item/update', params, method: 'post')
    convert_boolean(res)
  end

  def index
    res = execute_api('item/index', method: 'get')
    make_list(res)
  end

  def edit(params)
    res = execute_api('item/edit', params, method: 'get')
    make_data(res)
  end

  def delete # rubocop:disable Lint/DuplicateMethods
    execute_api('item/delete', {id: @id}, method: 'post')
  end

  private
  def item_params
    images = []
    (1..4).each do |num|
      images.push("@image#{num}")
    end

    images.push(@images)
    {
      name: @name,
      price: @price,
      description: @description,
      postage: @postage,
      inventory: @inventory,
      maji_flag: @maji_flag,
      action: @action,
      category_id: @category_id,
      images: images
      }
  end
end

div/app/controllers/items_controller.rb
# frozen_string_literal: true

require 'base64'
Dotenv.load
ACCESS_KEY = ENV.fetch('ACCESS_KEY_ID', nil)
SECRET_KEY = ENV.fetch('SECRET_ACCESS_KEY', nil)
REGION = 'ap-northeast-1'
BUCKET = 'maji-image'
class ItemsController < ApplicationController # rubocop:disable Style/Documentation
  def new
    @item_instance = Item.new
    @prm = {
      file_name: nil,
      ctype: nil
    }
  end

  def create
    @item_instance = Item.new(item_params)
    item_params['maji_flag'] = item_params['maji_flag'].to_i == 1
    res = @item_instance.create(item_params)
    if res == true
      redirect_to item_index_path, notice: '商品が登録されました'
    else
      render action: 'new'
    end
  end

  def index
    data = Item.new
    @items = Kaminari.paginate_array(data.index).page(params[:page])
  end

  def edit
    @item_instance = Item.new
    @item = get_item(params.permit(:id), @item_instance)
    redirect_to item_index_path, alert: @item[:err_message] if @item[:err_message].present?
  end

  def update
    @item_instance = Item.new(item_params)
    item_params['maji_flag'] = item_params['maji_flag'].to_i == 1
    @item = get_item(item_params, @item_instance)
    res = @item_instance.update(item_params)
    if res == true
      redirect_to item_index_path, notice: '商品が編集されました'
    else
      render action: 'edit'
    end
  end

  def delete
    @item_instance = Item.new(params.permit(:id))
    res = @item_instance.delete
    if res.key?('id')
      redirect_to item_index_path, notice: '商品が削除されました'
    else
      redirect_to item_index_path, alert: res["err_message"]
    end

  end

  private

  def item_params
    images = []
    (1..4).each do |num|
      images.push(params['item']["image#{num}"])
    end
    params.require(:item).permit(
      :id,
      :name,
      :price,
      :description,
      :postage,
      :inventory,
      :maji_flag,
      :action
    ).merge!(images: images)
  end

  def get_s3_resource(access_key, secret_key, region)
    Aws::S3::Resource.new(
      access_key_id: access_key,
      secret_access_key: secret_key,
      region: region
    )
  end

  def get_item(id, item)
    item.edit(id)
  end
end

div/app/helpers/item_helper.rb
module ItemHelper

  def s3_first_image(signer, image)

    image = signer.presigned_url(:get_object,
        bucket: BUCKET, 
        key: "item/#{image[0]["name"]}", 
        expires_in: 60)
    
  end
end

div/app/views/items/edit.html.erb
<div class="container mt-5">
  <h2>商品編集</h2>
  <%= render 'layouts/error', model: @item_instance %>
  <%= form_for @item_instance, url: {action: :update}, multipart: true do |f| %>
    <%=  f.hidden_field :id, value: @item[:id] %>
    <%=  f.hidden_field :action , value: :update %>
    <div class="mb-3">
      <%= f.label :name, "商品名", class: 'form-label' %>
      <%=  f.text_field :name, value: @item[:name],required: true,class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :price, "値段" ,class: 'form-label' %>
      <%=  f.text_field :price, value: @item[:price],required: true,class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= f.label :postage, "送料",class: 'form-label' %>
      <%=  f.text_field :postage, value: @item[:postage],class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :inventory, "在庫",class: 'form-label' %>
      <%=  f.text_field :inventory, value: @item[:inventory],class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :maji_flag, "新入荷",class: 'form-label' %>
      <%=  f.check_box :maji_flag, checked:  @item[:maji_flag] %>
    </div>
    <div class="mb-3">
      <%= f.label :description,"アピールコメント", class: 'form-label' %>
      <%=  f.text_area :description, value: @item[:description],class: 'form-control' %>
    </div>
    <% (1..4).each_with_index do |num, idx| %>
      <div class="mb-3">
        <%= f.label :image,"商品画像", class: "form-label#{num}" %><span>(バイト数:</span><span class="js-byte-preview<%= num %>">)</span>
        <%= f.file_field "image#{num}".to_sym ,include_hidden: false, class: "form-control js-input-#{num}" %>
        <img src="<%= @item[:"image_path0#{idx + 1}"] %>" alt="" class="js-previewImage-<%= num %> preview-format">
      </div>
    <% end %>
    <div class="mt-3" style="margin-top: 20px;">
      <%= submit_tag "商品登録",class: "btn btn-primary mb-5" %>
    </div>
  <% end %>
</div>

div/app/views/items/index.html.erb
<%= render partial: 'layouts/flash_message' %>
<div class="container mt-5">
    <h2>商品一覧</h2>

    <div class="item-container">
      <% @items.each do |it| %>
        <a href="<%= edit_item_path(it[:id]) %>" class="card item-card" style="width: 18rem;">
          <img src="<%= it[:image_path01] %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= it[:name] %></h5>
            <%= form_with url: delete_item_path(it[:id]), method: :post, data: { turbo_confirm: "本当に削除しますか？" }, local: true, class: 'delete-form' do %>
              <%= submit_tag "削除", class: 'btn btn-secondary delete-button' %>
            <% end %>
          </div>
        </a>
      <% end %>
    </div>
    <%= paginate @items, theme: 'twitter-bootstrap-4' %>
</div>

div/app/views/items/new.html.erb
<div class="container mt-5">
  <h2>商品登録</h2>
  <%= render 'layouts/error', model: @item_instance %>
  <%= form_for @item_instance, url: {action: :create}, multipart: true do |f| %>
    <%=  f.hidden_field :action , value: :create %>
    <div class="mb-3">
      <%= f.label :name, "商品名", class: 'form-label' %>
      <%=  f.text_field :name, placeholder: '',required: true,class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :price, "値段" ,class: 'form-label' %>
      <%=  f.text_field :price, placeholder: '',required: true,class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :postage, "送料", class: 'form-label' %>
      <%=  f.text_field :postage,class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :inventory, "在庫", class: 'form-label' %>
      <%=  f.text_field :inventory, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :maji_flag, "新入荷",class: 'form-label' %>
      <%=  f.check_box :maji_flag %>
    </div>
    <div class="mb-3">
      <%= f.label :description, "アピールコメント", class: 'form-label' %>
      <%=  f.text_area :description,class: 'form-control' %>
    </div>
    <% (1..4).each_with_index do |num, idx| %>
      <div class="mb-3">
        <%= f.label :image, "商品画像",class: "form-label#{num}" %><span>(バイト数:</span><span class="js-byte-preview<%= num %>">)</span>
        <%= f.file_field "image#{num}".to_sym ,include_hidden: false, class: "form-control js-input-#{num}" %>
        <img src="" alt="" class="js-previewImage-<%= num %> preview-format">
      </div>
    <% end %>
    <div class="mt-3" style="margin-top: 20px;">
      <%= submit_tag "商品登録",class: "btn btn-primary mb-5" %>
    </div>
  <% end %>
</div>